### ISSUE TITLE
Zero setup instructions available

### ISSUE THREAD

**Issue by Umisyus** [NdoleStudio/httpsms#361] opened 2024-02-17 03:40 UTC
Thanks for making this software. People using this need to know how to setup your app. What services do we need to setup? Where do configuration keys and options need to be placed? What commands need to be run to use the program?

_**Nothing.**_

After a while of configuration I finally have it up and running.
I'd gladly make a tutorial since there seems to be a need for one.

**Comment by AchoArnold** [comment] 2024-02-17 06:44
Hello @Umisyus 

Thanks for the suggestion. This is already a duplicate of #42

**Closed** 2024-02-17 06:44 UTC
